### ISSUE TITLE
demo 启动错误

### ISSUE THREAD

**Issue by 1404276788** [cunzaizhuyi/svelte-ui-template#1]
The plugin "vite:dep-scan" was triggered by this import

    script:E:/www/demo3/svelte-ui-template/src/App.svelte?id=0:6:7:
      6 │ import '@/lib/Counter.svelte'
        ╵        ~~~~~~~~~~~~~~~~~~~~~~

**Comment by cunzaizhuyi** [comment]
没有复现，请问你现在解决了吗？

**Comment by 1404276788** [comment]
解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月17日(周三) 下午5:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cunzaizhuyi/svelte-ui-template] demo 启动错误 (Issue #1)




 
没有复现，请问你现在解决了吗？

**Comment by cunzaizhuyi** [comment]
啥问题啊

**Comment by 1404276788** [comment]
`tsconfig.json` 文件
![image](https://user-images.githubusercontent.com/38417576/185103420-3680c564-e01b-4f5d-81c2-4cd86fa75828.png)
`vite.config.ts` 文件
![image](https://user-images.githubusercontent.com/38417576/185103505-783809dd-439f-4801-b55f-924b74d884f5.png)
